---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-cassandra-deadnode-recovery-complete
- name: Clear replace_address from defaults.sh
  lineinfile:
    state: absent
    regexp: '^{{ item }}'
    dest: "{{ apigee_installation_home }}/etc/defaults.sh"
  with_items:
  - 'JVM_OPTS="$JVM_OPTS.*-Dcassandra.replace_address'
